// ==UserScript==
// @name         中介大師 V87.5 - 確認發送版
// @namespace    http://tampermonkey.net/
// @version      87.5
// @description  流程：申請頁抓取(含無新訊息自動用最近記錄)→自動跳agent→貼入→等確認→按下一案自動發送
// @match        *://*/*
// @grant        window.close
// @grant        GM_setValue
// @grant        GM_getValue
// @grant        GM_setClipboard
// @run-at       document-end
// @allFrames    false
// ==/UserScript==

(function () {
    'use strict';

    // =========================================================================
    // 【A. 全域設定】
    // =========================================================================
    const MY_NAME_KEYWORDS = [
        "グローバルトラストネットワークス", "大阪支店", "池袋支店",
        "GTN", "仲介", "中介", "本人", "貴社", "シラトリ", "GTN FUNG",
        "株式会社", "Agent", "助手"
    ];

    const DISCLAIMER = `
------------------------------------------
AI 自動化信息更新助手 / AI Status Update
【中文】您好，此訊息由 AI 自動化工具生成。
【English】Hello, this message is generated by an AI automation tool.
【日本語】本情報はAIツールによる自動更新です。
------------------------------------------`;

    const INTRO_ZH = `【AI 自動化信息更新助手 / AI Status Update Helper】
您好，此訊息由 AI 自動化工具生成，旨在即時為您更新管理公司的最新動態。
📌 更新規則：若今日有新進展，系統將推送今日最新訊息；若今日暫無更新，系統將為您顯示最近三條對話紀錄以供回顧。

若您對訊息內容有任何疑問，請隨時提出，您的擔當經紀會為您做詳細說明。若您已明白意思，請進行相應的確認或對應；若您已經完成相關手續，則可以無視此訊息。`;

    const INTRO_EN = `Hello, this message is generated by an AI automation tool.
📌 Rule: If there is an update today, the system will send the latest messages from today. If there is no update today, the system will display the last three conversation records for your review.

If you have any questions, please contact your agent for a detailed explanation. If you understand the message, please proceed with the necessary confirmation or response; if you have already completed the process, please disregard this message.`;

    const BORDER = "━━━━━━━━━━━━━━━━━━━━━━━━";

    const QUICK_TEMPLATES = {
        "🔍 最短入居日": "お世話になっております。本物件の最短入居可能日をご教示いただけますでしょうか。",
        "🌍 海外審查告知": "お世話になっております。入国前のため在留カードは取得次第提出いたします。",
        "📶 上網環境確認": "インターネット環境（Wi-Fi/光回線）の導入状況を教えていただけますか。",
        "🚀 進度催促": "お世話になっております。現在の進捗状況を教えていただけますでしょうか。",
        "💰 AD 入金確認": "ADのご入金予定日についてお伺いできますでしょうか。",
        "🤝 承知いたしました": "お世話になっております。承知いたしました。引き続きよろしくお願いいたします。"
    };

    // 頁面類型
    const currentURL = window.location.href;
    const isSalesforce = currentURL.includes('force.com') || currentURL.includes('lightning.force.com');
    const isAgentPage = currentURL.includes('agent.best-estate.jp/cases/detail/');
    const isAppPage = (
        currentURL.includes('moushikomi') ||
        currentURL.includes('itandi') ||
        currentURL.includes('web_applications') ||
        currentURL.includes('mediate') ||
        currentURL.includes('entry_heads') ||
        currentURL.includes('go-web.jp') ||
        currentURL.includes('goweb.work') ||
        currentURL.includes('ielove.jp')
    );

    let PLATFORM = 'unknown';
    if (currentURL.includes('itandi') || currentURL.includes('moushikomi')) PLATFORM = 'ITANDI';
    else if (currentURL.includes('go-web.jp') || currentURL.includes('goweb.work')) PLATFORM = 'GoWeb';
    else if (currentURL.includes('ielove.jp')) PLATFORM = 'Ielove';
    else if (isSalesforce) PLATFORM = 'Salesforce';


    // =========================================================================
    // 【B. XHR 攔截 (Salesforce)】
    // =========================================================================
    if (isSalesforce) {
        const origOpen = XMLHttpRequest.prototype.open;
        const origSend = XMLHttpRequest.prototype.send;
        XMLHttpRequest.prototype.open = function (m, u) {
            this._v87url = u;
            return origOpen.apply(this, arguments);
        };
        XMLHttpRequest.prototype.send = function () {
            this.addEventListener('load', function () {
                try {
                    if (this._v87url && this._v87url.includes('runReport') &&
                        this.responseText && this.responseText.includes('agent.best-estate')) {
                        const queue = parseReportData(this.responseText);
                        if (queue.length > 0) {
                            window._v87Queue = queue;
                            const s = document.getElementById('v87-status');
                            if (s) s.innerText = '✅ 已載入 ' + queue.length + ' 個案件';
                            updateProgress();
                            updateCaseCount(queue.length);
                        }
                    }
                } catch (e) {}
            });
            return origSend.apply(this, arguments);
        };
    }

    function parseReportData(responseText) {
        try {
            const d = JSON.parse(responseText);
            const rows = d.actions[0].returnValue.factMap['T!T'].rows;
            return rows.map((row, i) => {
                const a = row.dataCells[0]?.label || '';
                const b = row.dataCells[1]?.label || '';
                const appUrl = (a.match(/title="(https?:\/\/[^"\s]+)/) || [])[1] || '';
                const agentUrl = (b.match(/title="(https?:\/\/[^"\s]+)/) || b.match(/href="(https?:\/\/[^"]+)"/) || [])[1] || '';
                return { i: i + 1, app: appUrl, agent: agentUrl };
            }).filter(r =>
                r.app && r.app !== '-' && r.app.trim() !== '' &&
                r.agent && r.agent.includes('agent.best-estate.jp')
            );
        } catch (e) { return []; }
    }


    // =========================================================================
    // 【C. 翻譯引擎】
    // =========================================================================
    async function translateText(text, targetLang) {
        if (!text || !text.trim() || text.length < 2 || /\.(jpg|png|pdf)/i.test(text)) return text;
        try {
            const url = 'https://translate.googleapis.com/translate_a/single?client=gtx&sl=ja&tl=' + targetLang + '&dt=t&q=' + encodeURIComponent(text);
            const res = await fetch(url);
            const data = await res.json();
            return data[0].map(item => item[0]).join('');
        } catch (e) { return '[翻譯失敗]'; }
    }


    // =========================================================================
    // 【D. 防閃退填表引擎】
    // =========================================================================
    window.V87_AUTOFILL = function (content) {
        const selectors = [
            '.itandi-bb-ui__ChatInput textarea',
            'textarea#ApplicationCommentComment',
            '#cloud_chat_input_area textarea',
            'textarea', '.chat-input', '#message_body',
            '[role="textbox"]', '[contenteditable="true"]'
        ];
        let box = null;
        for (let s of selectors) { box = document.querySelector(s); if (box) break; }

        if (box) {
            const lastValue = box.value || box.innerText || '';
            if (box.tagName === 'TEXTAREA' || box.tagName === 'INPUT') {
                box.value = content;
                if (box._valueTracker) box._valueTracker.setValue(lastValue);
                box.dispatchEvent(new Event('input', { bubbles: true }));
                box.dispatchEvent(new Event('change', { bubbles: true }));
            } else {
                box.innerText = content;
                box.dispatchEvent(new Event('input', { bubbles: true }));
            }
            box.focus();
            if (box.scrollTop !== undefined) box.scrollTop = box.scrollHeight;
            return true;
        } else {
            GM_setClipboard(content);
            alert('✅ 找不到輸入框，內容已複製到剪貼板！');
            return false;
        }
    };


    // =========================================================================
    // 【E. 日期工具】
    // =========================================================================
    function getTodayStrings() {
        const t = new Date();
        const y = t.getFullYear();
        const m = String(t.getMonth() + 1).padStart(2, '0');
        const d = String(t.getDate()).padStart(2, '0');
        return [
            y + '/' + m + '/' + d,
            y + '-' + m + '-' + d,
            y + '年' + (t.getMonth() + 1) + '月' + t.getDate() + '日',
            m + '/' + d,
            String(t.getMonth() + 1) + '/' + String(t.getDate())
        ];
    }

    function isToday(dateStr) {
        if (!dateStr) return false;
        return getTodayStrings().some(p => dateStr.includes(p));
    }


    // =========================================================================
    // 【F. 多平台抓取引擎】
    // =========================================================================
    function extractRawMessages() {
        let rawData = [];

        // 插槽 A: ITANDI
        if (PLATFORM === 'ITANDI') {
            document.querySelectorAll('.itandi-bb-ui__ChatBalloon, [class*="ChatBalloon"]').forEach(b => {
                const sender = b.querySelector('.css-in3yi3, [class*="sender"]')?.innerText.split('\n')[0].trim() || '';
                let date = '';
                b.querySelectorAll('p, span').forEach(p => {
                    if (/\d{4}[\/\-]\d{2}/.test(p.innerText)) date = p.innerText.trim();
                });
                const content = b.querySelector('.css-y2ak5, [class*="content"]')?.innerText.trim() || '';
                if (content && !MY_NAME_KEYWORDS.some(k => sender.includes(k))) {
                    rawData.push({ sender, date, content });
                }
            });
        }

        // 插槽 B: GoWeb
        else if (PLATFORM === 'GoWeb') {
            document.querySelectorAll('table#application_comments tbody tr').forEach(row => {
                const cells = row.querySelectorAll('td');
                if (cells.length >= 6) {
                    const date = cells[0].innerText.trim();
                    const sender = (cells[1].innerText.trim() + ' ' + cells[2].innerText.trim()).trim();
                    const content = cells[5]?.innerText.trim() || '';
                    if (date && content && !MY_NAME_KEYWORDS.some(k => sender.includes(k))) {
                        rawData.push({ sender, date, content });
                    }
                }
            });
            if (rawData.length === 0) {
                document.querySelectorAll('tr').forEach(el => {
                    const text = el.innerText;
                    if (text.length > 10 && !MY_NAME_KEYWORDS.some(k => text.includes(k))) {
                        const content = el.querySelector('td:last-child, p')?.innerText.trim() || text.substring(0, 200);
                        const date = text.match(/\d{4}[\/\-]\d{1,2}[\/\-]\d{1,2}/)?.[0] || '';
                        if (content.length > 5) rawData.push({ sender: '管理公司', date, content });
                    }
                });
            }
        }

        // 插槽 C: Ielove
        else if (PLATFORM === 'Ielove') {
            let lastDate = '';
            Array.from(document.querySelector('#cloud_chat_area')?.children || []).forEach(node => {
                if (node.classList.contains('date')) lastDate = node.innerText.trim();
                if (node.classList.contains('chat-other')) {
                    const sender = node.querySelector('.other-user-name')?.innerText.trim() || '管理公司';
                    const time = node.querySelector('.timestamp-other')?.innerText.trim() || '';
                    const content = node.querySelector('p')?.innerText.trim() || '';
                    if (content && !MY_NAME_KEYWORDS.some(k => sender.includes(k))) {
                        rawData.push({ sender, date: lastDate + ' ' + time, content });
                    }
                }
            });
        }

        // 插槽 D: 通用 CSS
        if (rawData.length === 0) {
            const selectors = ['.chat-message', '.message-bubble', '.chat-bubble',
                '[class*="message"]', '[class*="chat"]', '.comment', '.timeline-item'];
            for (const sel of selectors) {
                const found = document.querySelectorAll(sel);
                if (found.length > 0) {
                    found.forEach(bubble => {
                        const text = (bubble.innerText || '').replace(/\s+/g, ' ').trim();
                        const dateEl = bubble.closest('[class*="date"]') || bubble.querySelector('[class*="date"]');
                        if (text.length > 5 && !MY_NAME_KEYWORDS.some(k => text.includes(k))) {
                            rawData.push({ sender: '', date: dateEl?.innerText || '', content: text });
                        }
                    });
                    break;
                }
            }
        }

        // 插槽 E: 地毯式保底
        if (rawData.length === 0) {
            document.querySelectorAll('div, td, span, li, p').forEach(el => {
                if (el.closest('#v87-god-layer') || el.closest('#v87-master-box')) return;
                const txt = (el.innerText || '').trim();
                if (txt.length > 10 && txt.length < 1000 && !MY_NAME_KEYWORDS.some(k => txt.includes(k))) {
                    const dateMatch = txt.match(/\d{4}[\/\-]\d{1,2}[\/\-]\d{1,2}/) || txt.match(/\d{1,2}[\/]\d{1,2}/);
                    rawData.push({ sender: '管理公司', date: dateMatch?.[0] || '', content: txt });
                }
            });
        }

        // 【✨ 追加讀取插槽位】

        return rawData;
    }

    function getTargetMessages() {
        const rawData = extractRawMessages();
        if (rawData.length === 0) return { items: [], isToday: false };
        const todayItems = rawData.filter(item => isToday(item.date));
        if (todayItems.length > 0) return { items: todayItems, isToday: true };
        return { items: rawData.slice(-3), isToday: false };
    }


    // =========================================================================
    // 【G. 報告生成】
    // =========================================================================
    async function buildTrilingualReport(items, isTodayFlag) {
        const results = [];
        for (let i = 0; i < items.length; i++) {
            const item = items[i];
            const zh = await translateText(item.content, 'zh-TW');
            const en = await translateText(item.content, 'en');
            const prefix = `🔹 【最新進度 ${i + 1}】\n`;
            const senderLine = item.sender ? `🏢 ${item.sender}\n` : '';
            const dateLine = item.date ? `📅 ${item.date}\n` : '';
            results.push({
                orig: `${prefix}${senderLine}${dateLine}💬 ${item.content}`,
                zh:   `${prefix}${senderLine}${dateLine}💬 ${zh}`,
                en:   `${prefix}${senderLine}${dateLine}💬 ${en}`
            });
        }
        const statusZH = isTodayFlag ? '✅ 【今日管理公司最新回覆】' : 'ℹ️ 【今日暫無新訊息，此為目前的最新進度】';
        const statusEN = isTodayFlag ? '✅ [Latest Update Today]' : 'ℹ️ [No updates today. Current progress summary]';

        return `${INTRO_ZH}\n\n${INTRO_EN}\n\n${BORDER}\n\n`
            + `📍 日文原文 / Japanese Original\n${results.map(r => r.orig).join('\n\n')}\n\n${BORDER}\n\n`
            + `📍 中文翻譯 / Chinese Translation\n${statusZH}\n${results.map(r => r.zh).join('\n\n')}\n\n${BORDER}\n\n`
            + `📍 English Translation\n${statusEN}\n${results.map(r => r.en).join('\n\n')}`;
    }

    // 翻譯並存入 GM storage（供 agent 頁讀取）
    async function buildAndStoreReport(items, isTodayFlag) {
        if (!items.length) {
            GM_setValue('v87_report', null);
            GM_setValue('v87_noNewMsg', false);
            return;
        }
        const report = await buildTrilingualReport(items, isTodayFlag);
        GM_setValue('v87_report', report);
        GM_setValue('v87_noNewMsg', !isTodayFlag);
    }


    // =========================================================================
    // 【H. 進度 / Overlay 工具】
    // =========================================================================
    function updateProgress() {
        const prog = document.getElementById('v87-prog');
        if (!prog) return;
        const idx = GM_getValue('v87_idx', 0);
        const total = (GM_getValue('v87_queue', [])).length;
        prog.innerText = total > 0 ? (idx + 1) + ' / ' + total : '0 / 0';
    }

    function updateCaseCount(n) {
        const el = document.getElementById('v87-case-count');
        if (el) el.innerText = n || 0;
    }

    function showOverlay(message, color) {
        let el = document.getElementById('v87-overlay');
        if (!el) {
            el = document.createElement('div');
            el.id = 'v87-overlay';
            el.style.cssText = [
                'position:fixed', 'bottom:30px', 'right:90px', 'z-index:2147483647',
                'background:rgba(20,30,40,0.96)', 'color:white', 'padding:14px 20px',
                'border-radius:12px', 'border:2px solid #e74c3c', 'font-family:sans-serif',
                'font-size:14px', 'max-width:320px', 'pointer-events:none',
                'box-shadow:0 4px 20px rgba(0,0,0,0.5)'
            ].join(';');
            document.body.appendChild(el);
        }
        el.style.borderColor = color || '#e74c3c';
        el.innerText = message;
        el.style.display = message ? 'block' : 'none';
    }

    function hideOverlay() {
        const el = document.getElementById('v87-overlay');
        if (el) el.style.display = 'none';
    }


    // =========================================================================
    // 【I. 任務啟動】
    // =========================================================================
    function startMission(mode, queue) {
        if (!queue || !queue.length) {
            alert('未有案件數據！請等報表載入或按強力加載。');
            return;
        }
        GM_setValue('v87_queue', queue);
        GM_setValue('v87_idx', 0);
        GM_setValue('v87_mode', mode);
        GM_setValue('v87_active', true);
        GM_setValue('v87_nextNow', false);
        GM_setValue('v87_report', null);
        GM_setValue('v87_noNewMsg', false);
        updateProgress();

        const status = document.getElementById('v87-status');
        if (status) status.innerText = '🚀 開始第 1 案...';

        // 打開第一個申請頁
        setTimeout(() => window.open(queue[0].app, '_blank'), 500);
    }

    // 前往下一案
    function goNextCase() {
        const q = GM_getValue('v87_queue', []);
        const nextIdx = GM_getValue('v87_idx', 0) + 1;
        if (nextIdx < q.length) {
            GM_setValue('v87_idx', nextIdx);
            GM_setValue('v87_report', null);
            GM_setValue('v87_noNewMsg', false);
            GM_setValue('v87_nextNow', false);
            updateProgress();
            const status = document.getElementById('v87-status');
            if (status) status.innerText = '🚀 開始第 ' + (nextIdx + 1) + ' 案...';
            window.open(q[nextIdx].app, '_blank');
        } else {
            GM_setValue('v87_active', false);
            alert('🎉 全部 ' + q.length + ' 個案件完畢！');
        }
    }


    // =========================================================================
    // 【J. 申請頁面：完整抓取流程】
    // =========================================================================
    // ★ 核心：申請頁完成後直接 window.location 跳去 agent 頁（同 tab）
    if (isAppPage) {
        setTimeout(async () => {
            if (!GM_getValue('v87_active', false)) return;

            // 登錄檢測
            const isLoginPage = (
                document.querySelector('input[type="password"]') !== null ||
                /login|signin|sign_in|auth|session/i.test(window.location.href) ||
                /ログイン|サインイン|パスワード/i.test(document.title)
            );
            if (isLoginPage) {
                showLoginPanel();
                return;
            }

            showOverlay('⏳ 正在抓取訊息... (等待頁面加載)', '#f39c12');

            // 等多 2 秒讓頁面動態內容加載
            await new Promise(r => setTimeout(r, 2000));

            const { items, isToday: todayFlag } = getTargetMessages();
            const q = GM_getValue('v87_queue', []);
            const idx = GM_getValue('v87_idx', 0);
            const agentUrl = q[idx]?.agent;

            if (!agentUrl) {
                showOverlay('⚠️ 找不到 Agent URL，跳至下一案...', '#e74c3c');
                setTimeout(() => {
                    hideOverlay();
                    GM_setValue('v87_nextNow', true);
                    window.close();
                }, 2500);
                return;
            }

            // 完全無訊息
            if (!items.length) {
                showOverlay('ℹ️ 無任何訊息，跳至下一案...', '#7f8c8d');
                GM_setValue('v87_report', null);
                GM_setValue('v87_noNewMsg', false);
                setTimeout(() => { hideOverlay(); window.location.href = agentUrl; }, 2000);
                return;
            }

            // 有訊息：翻譯並存報告
            if (todayFlag) {
                showOverlay('🔄 找到今日訊息，翻譯中...', '#27ae60');
            } else {
                showOverlay('🔄 今日無新訊息，翻譯最近記錄...', '#e67e22');
            }

            await buildAndStoreReport(items, todayFlag);

            showOverlay('✅ 完成！跳至案件頁...', '#27ae60');
            setTimeout(() => { hideOverlay(); window.location.href = agentUrl; }, 1200);

        }, 4000); // 等 4 秒讓申請頁完全加載
    }


    // =========================================================================
    // 【K. Agent 頁面：自動貼入 → 確認面板 → 按「下一案」自動發送再跳】
    // =========================================================================
    if (isAgentPage) {
        const mode = GM_getValue('v87_mode', 'manual');

        // 搵可見輸入框（唔理 tab，聊天框永遠係同一個）
        function findInputBox() {
            const selectors = [
                '[placeholder*="LINE"]',
                '[placeholder*="メッセージ"]',
                '[placeholder*="入力"]',
                '[placeholder*="message"]',
                '.itandi-bb-ui__ChatInput textarea',
                'textarea#ApplicationCommentComment',
                '#cloud_chat_input_area textarea',
                '[contenteditable="true"]',
                '[contenteditable]',
                'textarea',
                '[role="textbox"]',
                '.chat-input',
                '#message_body'
            ];
            for (const s of selectors) {
                const els = document.querySelectorAll(s);
                for (const el of els) {
                    if (el.offsetParent !== null && el.offsetWidth > 0 && el.offsetHeight > 0) return el;
                }
            }
            return null;
        }

        // 強化填入（contenteditable + textarea 都支援）
        function fillInputBox(box, content) {
            box.focus();
            const isEditable = box.contentEditable === 'true' || box.hasAttribute('contenteditable');
            if (isEditable) {
                box.innerText = '';
                box.focus();
                document.execCommand('selectAll', false, null);
                document.execCommand('insertText', false, content);
                if (!box.innerText.trim()) {
                    box.innerText = content;
                    box.dispatchEvent(new InputEvent('input', { bubbles: true, data: content }));
                }
            } else {
                const lastValue = box.value;
                const setter = Object.getOwnPropertyDescriptor(window.HTMLTextAreaElement.prototype, 'value')?.set
                    || Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype, 'value')?.set;
                if (setter) setter.call(box, content);
                else box.value = content;
                if (box._valueTracker) box._valueTracker.setValue(lastValue);
                box.dispatchEvent(new Event('input', { bubbles: true }));
                box.dispatchEvent(new Event('change', { bubbles: true }));
            }
            box.scrollTop = box.scrollHeight;
        }

        // 搵發送按鈕
        function findSendBtn() {
            const selectors = [
                'button[aria-label*="送信"]', 'button[aria-label*="send"]',
                'button[title*="送信"]', 'button[title*="send"]',
                'button[class*="send"]', 'button[class*="Send"]',
                'button[class*="Submit"]', 'button[type="submit"]',
                '.send-button', 'input[type="submit"]'
            ];
            for (const s of selectors) {
                const el = document.querySelector(s);
                if (el && el.offsetParent !== null) return el;
            }
            return null;
        }

        // 超時計數（最多等 30 秒搵唔到輸入框就放棄）
        let waitCount = 0;
        const MAX_WAIT = 25;

        const fillInterval = setInterval(() => {
            if (!GM_getValue('v87_active', false)) { clearInterval(fillInterval); return; }

            const report = GM_getValue('v87_report', null);

            // 完全無訊息 → 靜默跳下一案
            if (report === null) {
                clearInterval(fillInterval);
                showOverlay('ℹ️ 此案無訊息，自動前往下一案...', '#7f8c8d');
                setTimeout(() => { hideOverlay(); goNextCaseFromAgent(); }, 1800);
                return;
            }

            const target = findInputBox();

            if (target) {
                clearInterval(fillInterval);
                showOverlay('📋 自動貼入報告...', '#3498db');
                setTimeout(() => {
                    fillInputBox(target, report);
                    GM_setValue('v87_report', null);
                    hideOverlay();
                    if (mode === 'auto') {
                        setTimeout(() => { findSendBtn()?.click(); }, 1500);
                        setTimeout(() => goNextCaseFromAgent(), 3500);
                    } else {
                        showAgentConfirmPanel(target, findSendBtn);
                    }
                }, 800);
            } else {
                waitCount++;
                if (waitCount === 5) showOverlay('⏳ 等待聊天框加載...', '#f39c12');
                if (waitCount >= MAX_WAIT) {
                    clearInterval(fillInterval);
                    hideOverlay();
                    // 超時：顯示提示，讓用戶手動決定
                    showOverlay('⚠️ 搵唔到輸入框，請手動貼入後按「下一案」', '#e74c3c');
                    GM_setValue('v87_report', null);
                    showAgentConfirmPanel(null, findSendBtn);
                }
            }
        }, 1200);
    }

    // Agent 頁的「下一案」邏輯（通知 Salesforce 頁或直接開新 tab）
    function goNextCaseFromAgent() {
        // 策略：直接開新 tab（讓 Salesforce 監聽 v87_nextNow 去處理計數）
        GM_setValue('v87_nextNow', true);
        window.close();
    }


    // =========================================================================
    // 【L. Salesforce 列表頁：監聽 nextNow 信號】
    // =========================================================================
    if (isSalesforce) {
        setInterval(() => {
            if (GM_getValue('v87_active', false) && GM_getValue('v87_nextNow', false)) {
                GM_setValue('v87_nextNow', false);
                goNextCase();
            }
        }, 1500);
    }


    // =========================================================================
    // 【M. 面板 UI】
    // =========================================================================
    function showLoginPanel() {
        document.getElementById('v87-login-panel')?.remove();
        const nav = _makePanel('v87-login-panel', '#f39c12');
        nav.innerHTML = '<p style="font-size:20px;margin:0 0 5px;">🔐</p>'
            + '<p style="font-size:15px;font-weight:bold;color:#f39c12;margin:0 0 5px;">需要登錄</p>'
            + '<p style="font-size:13px;color:#ccc;margin:0 0 15px;">請手動登錄此平台，完成後按下方按鈕繼續</p>'
            + '<div style="display:flex;gap:10px;justify-content:center;flex-wrap:wrap;">'
            + _btn('v87-login-done', '#27ae60', '✅ 已登錄，繼續')
            + _btn('v87-login-skip', '#7f8c8d', '⏭️ 跳過此案')
            + _btn('v87-login-stop', '#ff4757', '🛑 終止')
            + '</div>';
        document.body.appendChild(nav);

        document.getElementById('v87-login-done').onclick = async () => {
            nav.remove();
            showOverlay('⏳ 重新抓取訊息...', '#f39c12');
            await new Promise(r => setTimeout(r, 1000));
            const { items, isToday: todayFlag } = getTargetMessages();
            const q = GM_getValue('v87_queue', []);
            const agentUrl = q[GM_getValue('v87_idx', 0)]?.agent;
            if (!agentUrl) { showOverlay('⚠️ 找不到 Agent URL', '#e74c3c'); setTimeout(() => { GM_setValue('v87_nextNow', true); window.close(); }, 2000); return; }
            if (!items.length) { GM_setValue('v87_report', null); GM_setValue('v87_noNewMsg', false); showOverlay('ℹ️ 無訊息，跳至下一案...', '#7f8c8d'); setTimeout(() => { window.location.href = agentUrl; }, 2000); return; }
            showOverlay('🔄 翻譯中...', '#3498db');
            await buildAndStoreReport(items, todayFlag);
            showOverlay('✅ 完成！跳至案件頁...', '#27ae60');
            setTimeout(() => { hideOverlay(); window.location.href = agentUrl; }, 1200);
        };
        document.getElementById('v87-login-skip').onclick = () => { nav.remove(); GM_setValue('v87_report', null); GM_setValue('v87_nextNow', true); window.close(); };
        document.getElementById('v87-login-stop').onclick = () => { GM_setValue('v87_active', false); nav.remove(); };
    }

    // showNoNewMsgPanel 已廢棄：申請頁已自動處理無新訊息情況（用最近記錄），
    // agent 頁只需顯示確認面板即可。

    // ★ 核心確認面板：報告已貼入，等用戶確認，按「發送並下一案」時自動發送再跳
    function showAgentConfirmPanel(inputBox, findSendBtn) {
        document.getElementById('v87-confirm-panel')?.remove();
        const nav = _makePanel('v87-confirm-panel', '#27ae60');
        nav.innerHTML = ''
            + '<p style="font-size:18px;margin:0 0 6px;">✅ 報告已自動填入</p>'
            + '<p style="font-size:13px;color:#aaa;margin:0 0 18px;">請確認內容無誤，<b style="color:#f1c40f;">按「發送並下一案」</b>即自動發送並跳至下一案</p>'
            + '<div style="display:flex;gap:10px;justify-content:center;flex-wrap:wrap;">'
            + _btn('v87-confirm-send', '#27ae60', '📤 發送並下一案')
            + _btn('v87-confirm-skip', '#7f8c8d', '⏭️ 不發送，下一案')
            + _btn('v87-confirm-auto', '#e67e22', '🚀 之後全自動')
            + _btn('v87-confirm-stop', '#ff4757', '🛑 終止')
            + '</div>';
        document.body.appendChild(nav);

        function doSend() {
            showOverlay('📤 發送中...', '#27ae60');
            // 試 Enter 鍵
            if (inputBox) {
                inputBox.focus();
                inputBox.dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', code: 'Enter', keyCode: 13, which: 13, bubbles: true }));
            }
            // 試發送按鈕（需要從 isAgentPage scope 拿，用全域搵）
            setTimeout(() => {
                const sendBtn = document.querySelector([
                    'button[aria-label*="送信"]', 'button[aria-label*="send"]',
                    'button[title*="送信"]', 'button[class*="send"]',
                    'button[class*="Send"]', 'button[class*="Submit"]',
                    'button[type="submit"]', '.send-button'
                ].join(','));
                if (sendBtn && sendBtn.offsetParent !== null) sendBtn.click();
            }, 300);
            setTimeout(() => { hideOverlay(); goNextCaseFromAgent(); }, 2000);
        }

        document.getElementById('v87-confirm-send').onclick = () => { nav.remove(); doSend(); };
        document.getElementById('v87-confirm-skip').onclick = () => { nav.remove(); goNextCaseFromAgent(); };
        document.getElementById('v87-confirm-auto').onclick = () => {
            if (confirm('確定之後全部自動化？\n（自動貼入 + 自動發送，無需確認）')) {
                GM_setValue('v87_mode', 'auto');
                nav.remove();
                doSend();
            }
        };
        document.getElementById('v87-confirm-stop').onclick = () => { GM_setValue('v87_active', false); nav.remove(); };
    }

    // 保留給登錄面板用的舊版面板（簡化）
    function showAgentManualPanel(message, showAutoSwitch) {
        document.getElementById('v87-agent-panel')?.remove();
        const nav = _makePanel('v87-agent-panel', '#e74c3c');
        nav.innerHTML = '<p style="margin:0 0 15px;font-size:14px;">' + message + '</p>'
            + '<div style="display:flex;gap:10px;justify-content:center;flex-wrap:wrap;">'
            + _btn('v87-agent-next', '#e74c3c', '➡️ 下一案')
            + _btn('v87-agent-stop', '#ff4757', '🛑 終止')
            + '</div>';
        document.body.appendChild(nav);
        document.getElementById('v87-agent-next').onclick = () => { nav.remove(); goNextCaseFromAgent(); };
        document.getElementById('v87-agent-stop').onclick = () => { GM_setValue('v87_active', false); nav.remove(); };
    }

    // 共用：生成面板 div
    function _makePanel(id, borderColor) {
        const el = document.createElement('div');
        el.id = id;
        el.style.cssText = [
            'position:fixed', 'top:20px', 'left:50%', 'transform:translateX(-50%)',
            'z-index:2147483647', 'background:rgba(20,30,40,0.97)', 'padding:22px 28px',
            'color:white', 'border-radius:14px', 'border:2px solid ' + (borderColor || '#e74c3c'),
            'font-family:sans-serif', 'min-width:320px', 'text-align:center',
            'box-shadow:0 6px 30px rgba(0,0,0,0.6)'
        ].join(';');
        return el;
    }

    function _btn(id, bg, text) {
        return `<button id="${id}" style="padding:10px 18px;background:${bg};color:white;border:none;border-radius:8px;cursor:pointer;font-weight:bold;font-size:13px;">${text}</button>`;
    }


    // =========================================================================
    // 【N. 主控 UI (Salesforce 神級浮球)】
    // =========================================================================
    function injectMainUI() {
        if (document.getElementById('v87-god-layer')) { updateProgress(); return; }

        const god = document.createElement('div');
        god.id = 'v87-god-layer';
        god.style.cssText = 'position:fixed;top:0;left:0;width:100vw;height:100vh;z-index:2147483647;pointer-events:none;';
        (document.body || document.documentElement).appendChild(god);

        // ── 細小觸發按鈕（平時只顯示呢個）──
        const trigger = document.createElement('div');
        trigger.id = 'v87-trigger';
        trigger.style.cssText = `
            position:fixed;right:0;top:50%;transform:translateY(-50%);
            width:22px;height:56px;
            background:linear-gradient(180deg,#e67e22,#d35400);
            border-radius:8px 0 0 8px;
            cursor:pointer;pointer-events:auto;
            box-shadow:-2px 0 8px rgba(0,0,0,0.4);
            display:flex;align-items:center;justify-content:center;
            border:1px solid rgba(255,255,255,0.2);border-right:none;
        `;
        trigger.innerHTML = '<span style="color:white;font-size:10px;writing-mode:vertical-rl;font-weight:bold;letter-spacing:1px;user-select:none;">V87</span>';

        // ── 彈出面板（預設隱藏）──
        const panel = document.createElement('div');
        panel.id = 'v87-main-panel';
        panel.style.cssText = `
            position:fixed;right:22px;top:50%;transform:translateY(-50%);
            width:300px;max-height:85vh;
            background:rgba(18,26,34,0.98);
            border:2px solid #e67e22;border-radius:14px 0 0 14px;
            padding:16px;box-shadow:-6px 0 30px rgba(0,0,0,0.65);
            display:none;flex-direction:column;gap:10px;
            color:#ecf0f1;font-family:sans-serif;
            overflow-y:auto;pointer-events:auto;
            backdrop-filter:blur(12px);
        `;

        // 揿觸發按鈕 → 開/關面板
        trigger.onclick = (e) => {
            e.stopPropagation();
            panel.style.display = panel.style.display === 'flex' ? 'none' : 'flex';
        };

        // 揿面板外任何地方 → 收起
        document.addEventListener('click', (e) => {
            if (panel.style.display === 'flex' && !panel.contains(e.target) && e.target !== trigger) {
                panel.style.display = 'none';
            }
        }, true);

        god.appendChild(trigger);
        god.appendChild(panel);

        panel.innerHTML = `
            <div style="text-align:center;">
                <b style="color:#e67e22;font-size:16px;">🔧 中介大師 V87.5</b>
                <div style="font-size:11px;color:#888;margin-top:2px;">平台：<span style="color:#f39c12;">${PLATFORM}</span></div>
            </div>

            <div style="background:rgba(0,0,0,0.35);padding:10px;border-radius:10px;text-align:center;">
                <div style="font-size:11px;color:#aaa;">已鎖定案件</div>
                <div id="v87-case-count" style="font-size:30px;font-weight:bold;color:#55efc4;">0</div>
                <div style="font-size:11px;color:#aaa;margin-top:4px;">進度：<b id="v87-prog" style="color:#55efc4;">0 / 0</b></div>
            </div>
            <div id="v87-status" style="font-size:11px;color:#f1c40f;text-align:center;min-height:14px;"></div>

            <!-- 🚀 自動化巡航（Salesforce 專用，其他頁面隱藏） -->
            <div id="v87-sf-section" style="background:rgba(52,73,94,0.5);border-radius:12px;padding:10px;border:1px solid rgba(255,255,255,0.08);display:${isSalesforce ? 'block' : 'none'};">
                <div style="font-weight:bold;color:#e67e22;font-size:13px;margin-bottom:8px;">🚀 自動化巡航</div>
                <button id="v87-manual-btn" style="width:100%;padding:11px;background:#3498db;color:white;border:none;border-radius:8px;cursor:pointer;font-weight:bold;margin-bottom:6px;">✋ 手動步進模式</button>
                <button id="v87-auto-btn" style="width:100%;padding:11px;background:#e74c3c;color:white;border:none;border-radius:8px;cursor:pointer;font-weight:bold;margin-bottom:6px;">⚡ 全自動模式</button>
                <button id="v87-load-btn" style="width:100%;padding:9px;background:#27ae60;color:white;border:none;border-radius:8px;cursor:pointer;font-weight:bold;margin-bottom:6px;">💪 強力加載數據</button>
                <button id="v87-reload-btn" style="width:100%;padding:8px;background:#16a085;color:white;border:none;border-radius:8px;cursor:pointer;font-size:12px;">🔄 刷新報表</button>
            </div>

            <!-- 📑 單頁報告（任何頁面都顯示） -->
            <div style="background:rgba(52,73,94,0.5);border-radius:12px;padding:10px;border:1px solid rgba(255,255,255,0.08);">
                <div style="font-weight:bold;color:#e67e22;font-size:13px;margin-bottom:8px;">📑 即時報告</div>
                <button id="v87-read-btn" style="width:100%;padding:11px;background:linear-gradient(to bottom,#e67e22,#d35400);color:white;border:none;border-radius:8px;cursor:pointer;font-weight:bold;">📋 抓取並複製三語報告</button>
            </div>

            <!-- 🖋️ 快捷申請（任何頁面都顯示） -->
            <div style="background:rgba(52,73,94,0.5);border-radius:12px;padding:10px;border:1px solid rgba(255,255,255,0.08);">
                <div style="font-weight:bold;color:#e67e22;font-size:13px;margin-bottom:8px;">🖋️ 快捷申請 / 催促</div>
                <div id="v87-quick-btns" style="display:flex;flex-direction:column;gap:6px;"></div>
            </div>

            <button id="v87-stop-btn" style="width:100%;padding:10px;background:#ff4757;color:white;border:none;border-radius:8px;cursor:pointer;font-weight:bold;">🛑 終止所有任務</button>
        `;

        // 快捷按鈕
        const quickBox = panel.querySelector('#v87-quick-btns');
        Object.keys(QUICK_TEMPLATES).forEach(t => {
            const b = document.createElement('button');
            b.innerText = t;
            b.style.cssText = 'width:100%;padding:9px;background:#2980b9;color:white;border:none;border-radius:7px;cursor:pointer;font-size:12px;text-align:left;';
            b.onclick = () => window.V87_AUTOFILL(QUICK_TEMPLATES[t]);
            quickBox.appendChild(b);
        });

        const status = panel.querySelector('#v87-status');

        // 手動步進
        panel.querySelector('#v87-manual-btn').onclick = () => {
            const q = window._v87Queue || GM_getValue('v87_queue', []);
            if (!q.length) { status.innerText = '⚠️ 等待報表載入...'; return; }
            startMission('manual', q);
        };

        // 全自動
        panel.querySelector('#v87-auto-btn').onclick = () => {
            const q = window._v87Queue || GM_getValue('v87_queue', []);
            if (!q.length) { status.innerText = '⚠️ 等待報表載入...'; return; }
            if (confirm('確定全自動執行 ' + q.length + ' 個案件？\n每案會自動貼入並發送，請確認！')) {
                startMission('auto', q);
            }
        };

        // 強力加載 (V67)
        panel.querySelector('#v87-load-btn').onclick = () => {
            const btn = panel.querySelector('#v87-load-btn');
            btn.innerText = '⏳ 強力加載中...';
            document.querySelectorAll('button[aria-expanded="false"], .slds-button_reset[title*="展開"]').forEach(b => b.click());
            let dist = 0;
            const scroll = setInterval(() => {
                window.scrollBy(0, 500); dist += 500;
                if (dist > 12000) {
                    clearInterval(scroll); window.scrollTo(0, 0);
                    btn.innerText = '✅ 加載完畢';
                    let links = [];
                    document.querySelectorAll('a').forEach(a => {
                        if (a.href && a.href.startsWith('http') && !a.href.includes('force.com') && !a.href.includes('best-estate.jp')) links.push(a.href);
                    });
                    updateCaseCount([...new Set(links)].length);
                    setTimeout(() => { btn.innerText = '💪 強力加載數據'; }, 3000);
                }
            }, 120);
        };

        // 刷新報表
        panel.querySelector('#v87-reload-btn').onclick = () => {
            const refreshBtn = document.querySelector('[title="更新"],[title="Refresh"],[data-aura-class*="refresh"]');
            if (refreshBtn) { refreshBtn.click(); status.innerText = '✅ 已觸發刷新...'; }
            else { status.innerText = '⚠️ 請手動刷新報表'; }
        };

        // 單頁報告
        panel.querySelector('#v87-read-btn').onclick = async () => {
            const btn = panel.querySelector('#v87-read-btn');
            btn.innerText = '⏳ 抓取中...'; btn.disabled = true;
            try {
                const { items, isToday: tf } = getTargetMessages();
                if (!items.length) { alert('❌ 找不到有效的管理公司回覆。'); }
                else {
                    btn.innerText = '🔄 翻譯中...';
                    const report = await buildTrilingualReport(items, tf);
                    GM_setClipboard(report);
                    btn.innerText = '✅ 已複製！';
                }
            } catch (e) { btn.innerText = '❌ 出錯，請重試'; }
            setTimeout(() => { btn.innerText = '📋 抓取並複製三語報告'; btn.disabled = false; }, 3000);
        };

        // 終止
        panel.querySelector('#v87-stop-btn').onclick = () => {
            GM_setValue('v87_active', false);
            status.innerText = '🛑 已終止';
        };

        updateProgress();
    }

    // 非 Salesforce：左上角獨立按鈕
    // =========================================================================
    // 【O. 啟動 UI - 任何頁面都用同一個浮球】
    // =========================================================================
    if (window.top !== window.self) return;

    // 唯一入口：任何頁面都注入同一個主控浮球
    function initUI() {
        injectMainUI();
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', initUI);
    } else {
        initUI();
    }

    // 保持浮球存在（防止被頁面覆蓋）
    setInterval(() => {
        if (!document.getElementById('v87-god-layer')) injectMainUI();
    }, 3000);

})();
